"""Initial migration

Revision ID: 45928917a5a1
Revises: 
Create Date: 2026-04-10 16:36:41.357689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45928917a5a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_guid', sa.String(length=36), nullable=True),
    sa.Column('data_subject_guid', sa.String(length=36), nullable=True),
    sa.Column('source_service', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload_snapshot', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)

    op.create_table('cambio_patient_map',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('pdhc_patient_guid', sa.String(length=36), nullable=False),
    sa.Column('cambio_patient_id', sa.String(length=128), nullable=True),
    sa.Column('cambio_ehr_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('cambio_patient_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cambio_patient_map_pdhc_patient_guid'), ['pdhc_patient_guid'], unique=True)

    op.create_table('dedupe_registry',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('source_service', sa.String(length=64), nullable=False),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('payload_hash', 'source_service', name='uq_dedupe_hash_service')
    )
    op.create_table('ingest_raw',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('source_service', sa.String(length=64), nullable=False),
    sa.Column('source_system_id', sa.String(length=64), nullable=True),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('headers_json', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('ingest_raw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_raw_patient_guid'), ['patient_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_raw_payload_hash'), ['payload_hash'], unique=False)

    op.create_table('loinc_archetype_map',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('loinc_code', sa.String(length=16), nullable=False),
    sa.Column('loinc_display', sa.String(length=128), nullable=True),
    sa.Column('archetype_id', sa.String(length=128), nullable=True),
    sa.Column('archetype_node_id', sa.String(length=32), nullable=True),
    sa.Column('canonical_metric', sa.String(length=64), nullable=True),
    sa.Column('canonical_unit', sa.String(length=32), nullable=True),
    sa.Column('canonical_table', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('loinc_archetype_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loinc_archetype_map_loinc_code'), ['loinc_code'], unique=False)

    op.create_table('service_keys',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('activities',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('ingest_raw_guid', sa.String(length=36), nullable=False),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=True),
    sa.Column('source_code', sa.String(length=32), nullable=True),
    sa.Column('source_service', sa.String(length=64), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingest_raw_guid'], ['ingest_raw.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_patient_guid'), ['patient_guid'], unique=False)

    op.create_table('clinical_context',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('ingest_raw_guid', sa.String(length=36), nullable=False),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('transaction_guid', sa.String(length=36), nullable=True),
    sa.Column('careplan_guid', sa.String(length=36), nullable=True),
    sa.Column('plandef_guid', sa.String(length=36), nullable=True),
    sa.Column('resolved_context_json', sa.JSON(), nullable=True),
    sa.Column('source_service', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingest_raw_guid'], ['ingest_raw.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('clinical_context', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_context_patient_guid'), ['patient_guid'], unique=False)

    op.create_table('fhir_resources',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('ingest_raw_guid', sa.String(length=36), nullable=False),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_json', sa.JSON(), nullable=False),
    sa.Column('loinc_code', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_service', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingest_raw_guid'], ['ingest_raw.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('fhir_resources', schema=None) as batch_op:
        batch_op.create_index('ix_fhir_patient_type_eff', ['patient_guid', 'resource_type', sa.literal_column('effective_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_resources_loinc_code'), ['loinc_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_fhir_resources_patient_guid'), ['patient_guid'], unique=False)

    op.create_table('health_observations',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('ingest_raw_guid', sa.String(length=36), nullable=False),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=True),
    sa.Column('source_code', sa.String(length=32), nullable=True),
    sa.Column('source_service', sa.String(length=64), nullable=True),
    sa.Column('concept_guid', sa.String(length=36), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingest_raw_guid'], ['ingest_raw.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('health_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_observations_concept_guid'), ['concept_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_observations_patient_guid'), ['patient_guid'], unique=False)

    op.create_table('openehr_compositions',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('ingest_raw_guid', sa.String(length=36), nullable=False),
    sa.Column('fhir_resource_guid', sa.String(length=36), nullable=True),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('archetype_id', sa.String(length=128), nullable=True),
    sa.Column('template_id', sa.String(length=128), nullable=True),
    sa.Column('composition_json', sa.JSON(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_service', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fhir_resource_guid'], ['fhir_resources.guid'], ),
    sa.ForeignKeyConstraint(['ingest_raw_guid'], ['ingest_raw.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    with op.batch_alter_table('openehr_compositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_openehr_compositions_patient_guid'), ['patient_guid'], unique=False)
        batch_op.create_index('ix_openehr_patient_arch_eff', ['patient_guid', 'archetype_id', sa.literal_column('effective_at DESC')], unique=False)

    op.create_table('cambio_delivery_log',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('ingest_raw_guid', sa.String(length=36), nullable=False),
    sa.Column('fhir_resource_guid', sa.String(length=36), nullable=True),
    sa.Column('openehr_comp_guid', sa.String(length=36), nullable=True),
    sa.Column('patient_guid', sa.String(length=36), nullable=False),
    sa.Column('delivery_type', sa.String(length=16), nullable=False),
    sa.Column('cambio_resource_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fhir_resource_guid'], ['fhir_resources.guid'], ),
    sa.ForeignKeyConstraint(['ingest_raw_guid'], ['ingest_raw.guid'], ),
    sa.ForeignKeyConstraint(['openehr_comp_guid'], ['openehr_compositions.guid'], ),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('ingest_raw_guid', 'delivery_type', name='uq_delivery_raw_type')
    )
    with op.batch_alter_table('cambio_delivery_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cambio_delivery_log_patient_guid'), ['patient_guid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cambio_delivery_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cambio_delivery_log_patient_guid'))

    op.drop_table('cambio_delivery_log')
    with op.batch_alter_table('openehr_compositions', schema=None) as batch_op:
        batch_op.drop_index('ix_openehr_patient_arch_eff')
        batch_op.drop_index(batch_op.f('ix_openehr_compositions_patient_guid'))

    op.drop_table('openehr_compositions')
    with op.batch_alter_table('health_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_observations_patient_guid'))
        batch_op.drop_index(batch_op.f('ix_health_observations_concept_guid'))

    op.drop_table('health_observations')
    with op.batch_alter_table('fhir_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fhir_resources_patient_guid'))
        batch_op.drop_index(batch_op.f('ix_fhir_resources_loinc_code'))
        batch_op.drop_index('ix_fhir_patient_type_eff')

    op.drop_table('fhir_resources')
    with op.batch_alter_table('clinical_context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_context_patient_guid'))

    op.drop_table('clinical_context')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_patient_guid'))

    op.drop_table('activities')
    op.drop_table('service_keys')
    with op.batch_alter_table('loinc_archetype_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loinc_archetype_map_loinc_code'))

    op.drop_table('loinc_archetype_map')
    with op.batch_alter_table('ingest_raw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_raw_payload_hash'))
        batch_op.drop_index(batch_op.f('ix_ingest_raw_patient_guid'))

    op.drop_table('ingest_raw')
    op.drop_table('dedupe_registry')
    with op.batch_alter_table('cambio_patient_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cambio_patient_map_pdhc_patient_guid'))

    op.drop_table('cambio_patient_map')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
