#!/usr/bin/env bash
# deploy/stamp.sh N — generate a `.env` file for cdr.pdhc instance N.
#
# Per platform-plan execution §3.1.b, never runs sudo and never touches
# the live server. The operator runs this locally to produce a `.env`
# (and a small directory tree of bookkeeping files), then copies the
# release tarball + .env to the macmini and brings the compose project
# up under `/usr/local/www/cdrN.pdhc/`.
#
# Port plan (from execution-plan §3.1.c):
#   CDR1: app=9046  db=9045   project=cdr_pdhc_1
#   CDR2: app=9146  db=9145   project=cdr_pdhc_2
#   CDR3: app=9246  db=9245   project=cdr_pdhc_3
#   CDR4: app=9346  db=9345   project=cdr_pdhc_4
#   CDR5: app=9446  db=9445   project=cdr_pdhc_5
#
# Each block is separated by 100 so Rule-16 kill-own-ports scripts can
# never touch a sibling (Rule 22). Each instance gets its own pgdata
# volume so `docker volume rm` in the wrong instance can't bleed into
# another.
#
# Usage:
#   deploy/stamp.sh 3                        # writes deploy/instances/cdr3/.env
#   deploy/stamp.sh 3 --out ./somewhere      # custom output dir
#   deploy/stamp.sh 3 --print                # print to stdout, no file
#
# The output `.env` is a template — secrets (POSTGRES_PASSWORD,
# CDR_AUTH_TOKEN, SSO_CLIENT_*, FLASK_SECRET_KEY) are emitted as empty
# strings the operator must fill in before bringing the project up.

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "usage: $0 <instance: 1..5> [--out <dir>] [--print]" >&2
    exit 1
fi

N="$1"; shift
case "$N" in
    1|2|3|4|5) ;;
    *) echo "instance must be 1..5; got: $N" >&2; exit 1;;
esac

OUT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/instances/cdr${N}"
PRINT_ONLY=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --out) OUT_DIR="$2"; shift 2;;
        --print) PRINT_ONLY=1; shift;;
        *) echo "unknown option: $1" >&2; exit 1;;
    esac
done

# Port-block computation: CDR1=9046/9045, CDRk=(9046 + 100*(k-1))/(9045 + 100*(k-1))
APP_PORT=$((9046 + 100 * (N - 1)))
DB_PORT=$((9045 + 100 * (N - 1)))
PROJECT_NAME="cdr_pdhc_${N}"
INSTANCE_LABEL="cdr_pdhc_${N}"
DB_VOLUME="cdr_pdhc_${N}_pgdata"
DB_NAME="cdr_db"
DB_USER="cdr_user"

ENV_BLOCK="$(cat <<EOF
# Generated by deploy/stamp.sh ${N} on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Per platform-plan execution §3.1 — one CDR instance of five.
# Operator must fill in every empty value before \`docker compose up\`.

# ----- compose-level identity (read by docker-compose.yml) -----
COMPOSE_PROJECT_NAME=${PROJECT_NAME}
CDR_INSTANCE=${INSTANCE_LABEL}
APP_PORT=${APP_PORT}
DB_PORT=${DB_PORT}
DB_VOLUME=${DB_VOLUME}

# ----- Postgres (compose creates the DB on first init) -----
POSTGRES_USER=${DB_USER}
POSTGRES_DB=${DB_NAME}
POSTGRES_PASSWORD=

# ----- Flask app -----
FLASK_SECRET_KEY=
DATABASE_URL=postgresql://${DB_USER}:\${POSTGRES_PASSWORD}@db:5432/${DB_NAME}

# ----- SSO (Rule 19 — operator-owned secrets) -----
# See platform-plan §3.2: each instance's pair must already exist in
# sso.pdhc/.env as SSO_CLIENT_ID_CDR${N} / SSO_CLIENT_SECRET_CDR${N}.
AUTH_MODE=sso
SSO_BASE_URL=https://sso.pdhc.se
SSO_CLIENT_ID=
SSO_CLIENT_SECRET=
SSO_CALLBACK_URL=https://cdr${N}.pdhc.se/auth/callback

# ----- Service-key auth from sibling services -----
GATEWAY_PDHC_SERVICE_KEY=
TWOGATE_PDHC_SERVICE_KEY=

# ----- Vocabulary stack -----
TERMBANK_BASE_URL=http://127.0.0.1:9012
XLATE_BASE_URL=http://127.0.0.1:9017
PLAN_BASE_URL=http://127.0.0.1:9030

# ----- Mapping version stamp -----
# Bumped when the workgroup adopts a new plan.pdhc Concept set. Stored on
# every resource row's mapping_version column (platform-plan §1.2.j).
MAPPING_VERSION=

# ----- Cambio sandbox (CDR1 only — leave empty for CDR2..5) -----
CAMBIO_DELIVERY_ENABLED=false
CAMBIO_CLIENT_ID=
CAMBIO_CLIENT_SECRET=
CAMBIO_TOKEN_URL=
CAMBIO_BASE_URL=
CAMBIO_TENANT=
CAMBIO_COMMISSION_HSA_ID=
CAMBIO_HEALTHCARE_UNIT_HSA_ID=
CAMBIO_HEALTHCARE_PROVIDER_HSA_ID=
CAMBIO_ORG_ID=
EOF
)"

if [[ "$PRINT_ONLY" -eq 1 ]]; then
    echo "$ENV_BLOCK"
    exit 0
fi

mkdir -p "$OUT_DIR"
echo "$ENV_BLOCK" > "$OUT_DIR/.env"
echo "wrote $OUT_DIR/.env"
echo
echo "next steps for instance ${N}:"
echo "  1. fill in POSTGRES_PASSWORD, FLASK_SECRET_KEY, SSO_CLIENT_ID,"
echo "     SSO_CLIENT_SECRET, GATEWAY_PDHC_SERVICE_KEY, MAPPING_VERSION"
echo "  2. SSO operator action: register cdr${N}.pdhc.se callback URL"
echo "     and SSO_CLIENT_ID_CDR${N} / SSO_CLIENT_SECRET_CDR${N} in"
echo "     sso.pdhc/.env (see platform-plan §3.2)"
echo "  3. nginx operator action: add a server block for cdr${N}.pdhc.se"
echo "     proxying to 127.0.0.1:${APP_PORT} (see platform-plan §3.3)"
echo "  4. tarball this repo (without venv/.env), scp to miserver,"
echo "     extract under /usr/local/www/cdr${N}.pdhc/releases/<ts>/,"
echo "     drop \`.env\` next to docker-compose.yml, point \`current\`"
echo "     symlink at the new release, run \`docker compose up -d\`"
